version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: compose
    command: npm run serve
    ports:
      - "8080:8080"
    container_name: frontend
    networks:
      - super_network

networks:
  super_network:
    external:
      name: super_network
